# Generated by Django 3.2.3 on 2021-06-19 17:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_reviews_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(blank=True, max_length=30)),
                ('CNIC', models.CharField(blank=True, max_length=13)),
                ('PhoneNo1', models.CharField(blank=True, max_length=13)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('EntryDate', models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 19, 10, 42, 15, 587845))),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalBill', models.DecimalField(decimal_places=2, max_digits=8)),
                ('EntryDate', models.DateTimeField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DistributerBrandDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=30, unique=True)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.CharField(blank=True, max_length=50, unique=True)),
                ('PhoneNo', models.CharField(max_length=13, unique=True)),
                ('EntryDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DistributerPersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('FatherName', models.CharField(max_length=30)),
                ('CNIC', models.CharField(blank=True, max_length=13, unique=True)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=8)),
                ('MaritalStatus', models.CharField(max_length=10)),
                ('EntryDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePesonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(blank=True, max_length=30)),
                ('CNIC', models.CharField(blank=True, max_length=13, unique=True)),
                ('FatherName', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=8)),
                ('MaritalStatus', models.CharField(max_length=10)),
                ('EntryDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(max_length=30, unique=True)),
                ('FoodType', models.CharField(max_length=50)),
                ('FoodDescription', models.CharField(blank=True, max_length=100)),
                ('EntryDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodSize', models.CharField(max_length=10)),
                ('FoodPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('EntryDate', models.DateTimeField()),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.food')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IngredientName', models.CharField(max_length=30, unique=True)),
                ('IngredientPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Size', models.CharField(blank=True, max_length=10)),
                ('Description', models.CharField(blank=True, max_length=100)),
                ('EntryDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30, unique=True)),
                ('Email', models.CharField(max_length=50)),
                ('EntryDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfferName', models.CharField(max_length=30, unique=True)),
                ('OfferPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Availability', models.CharField(blank=True, max_length=10)),
                ('CreateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='product_insert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('Product_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='productimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(blank=True, max_length=30)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('PhoneNo2', models.CharField(blank=True, max_length=13)),
                ('EntryDate', models.DateTimeField(default=datetime.datetime(2021, 6, 19, 10, 42, 15, 603483))),
                ('numberofguests', models.CharField(blank=True, max_length=13)),
                ('Timefrom', models.CharField(max_length=10)),
                ('TimeTo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DegreeName', models.CharField(max_length=50)),
                ('InstituteName', models.CharField(max_length=50)),
                ('PassingYear', models.CharField(blank=True, max_length=10)),
                ('ObtainedMarks', models.IntegerField()),
                ('TotalMarks', models.IntegerField()),
                ('Grade', models.CharField(blank=True, max_length=2)),
                ('Other', models.CharField(blank=True, max_length=100)),
                ('EntryDate', models.DateTimeField()),
                ('EmployeePID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employeepesonaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchasePrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Quantity', models.IntegerField()),
                ('Size', models.CharField(blank=True, max_length=10)),
                ('PurchaseDate', models.DateTimeField()),
                ('BrandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.distributerbranddetail')),
                ('IngredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='OffersFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('EntryDate', models.DateTimeField()),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.food')),
                ('FoodSizeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.foodsize')),
                ('OfferID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.offers')),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('LoginTime', models.DateTimeField()),
                ('LoginID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.login')),
            ],
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Size', models.CharField(max_length=10)),
                ('EntryDate', models.DateTimeField()),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.food')),
                ('FoodSizeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.foodsize')),
                ('IngredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExtrasName', models.CharField(max_length=30)),
                ('ExtrasType', models.CharField(max_length=10)),
                ('ExtrasQuantity', models.IntegerField(blank=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Description', models.CharField(max_length=250)),
                ('EntryDate', models.DateTimeField()),
                ('EmployeePID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employeepesonaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillName', models.CharField(max_length=50)),
                ('OrganizationName', models.CharField(max_length=50)),
                ('CertificationNumber', models.CharField(blank=True, max_length=50)),
                ('LearnStartDate', models.DateField()),
                ('LearnEndDate', models.DateField()),
                ('Others', models.CharField(blank=True, max_length=100)),
                ('EntryDate', models.DateTimeField()),
                ('EmployeePID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employeepesonaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePrevoiusExperiance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationName', models.CharField(max_length=50)),
                ('JobName', models.CharField(max_length=50)),
                ('JobDescription', models.CharField(blank=True, max_length=100)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Others', models.CharField(blank=True, max_length=100)),
                ('EntryDate', models.DateTimeField()),
                ('EmployeePID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employeepesonaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('PhoneNo1', models.CharField(max_length=13, unique=True)),
                ('LandLineNo', models.CharField(blank=True, max_length=15)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('EntryDate', models.DateTimeField()),
                ('EmployeePID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employeepesonaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobName', models.CharField(max_length=30)),
                ('EmployeementYears', models.IntegerField()),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Bonus', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DutyStartTime', models.TimeField(blank=True)),
                ('DutyEndTime', models.TimeField(blank=True)),
                ('JobDescription', models.CharField(max_length=100)),
                ('EntryDate', models.DateTimeField()),
                ('EmployeePID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employeepesonaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='DistributerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaidAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('RemaningAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('PaymentType', models.CharField(max_length=13)),
                ('EntryDate', models.DateTimeField()),
                ('DistributerPID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.distributerpersonaldetail')),
                ('PurchaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productpurchase')),
            ],
        ),
        migrations.CreateModel(
            name='DistributerContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=13)),
                ('LandLineNo', models.CharField(blank=True, max_length=15)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('Others', models.CharField(blank=True, max_length=100)),
                ('EntryDate', models.DateTimeField()),
                ('DistributerPID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.distributerpersonaldetail')),
            ],
        ),
        migrations.AddField(
            model_name='distributerbranddetail',
            name='DistributerPID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.distributerpersonaldetail'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryAddress', models.CharField(max_length=100)),
                ('ExpectedTime', models.CharField(max_length=10)),
                ('EntryDate', models.DateTimeField()),
                ('CustomerOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customerorderbooking')),
                ('EmployeePID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employeepesonaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentMedium', models.CharField(max_length=50)),
                ('PaymentAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('EntryDate', models.DateTimeField()),
                ('CustomerOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customerorderbooking')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=30)),
                ('ProductSize', models.CharField(max_length=10)),
                ('ProductQuantity', models.IntegerField()),
                ('SalePrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('EntryDate', models.DateTimeField()),
                ('CustomerOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customerorderbooking')),
            ],
        ),
        migrations.AddField(
            model_name='customerorderbooking',
            name='EmployeePID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employeepesonaldetail'),
        ),
        migrations.CreateModel(
            name='CurrentStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('EntryDate', models.DateTimeField()),
                ('IngredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
            ],
        ),
    ]
